-- MySQL Script generated by MySQL Workbench
-- Wed Apr  1 15:01:24 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema moosong
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema moosong
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `moosong` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `moosong` ;

-- -----------------------------------------------------
-- Table `moosong`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moosong`.`course` (
  `c_code` CHAR(4) NOT NULL,
  `c_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`c_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moosong`.`lecture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moosong`.`lecture` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `l_name` VARCHAR(100) NOT NULL,
  `start_at` DATE NOT NULL DEFAULT DATE(CURRENT_TIMESTAMP),
  `c_code` CHAR(4) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lecture_course_idx` (`c_code` ASC) VISIBLE,
  CONSTRAINT `fk_lecture_course`
    FOREIGN KEY (`c_code`)
    REFERENCES `moosong`.`course` (`c_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
